module: AppLaunch
author: IBM
github_url: https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-applaunch

skip_undocumented: false
clean: true
hide_documentation_coverage: true


custom_categories:
  - name: Client
    children:
    - AppLaunch
    - AppLaunchConfig
    - AppLaunchUser

  - name: Response
    children:
    - AppLaunchResponse
    - AppLaunchFailResponse

  - name: Enumerators and TypeAlias
    children:
      - ICRegion
      - RefreshPolicy
      - ErrorCode
      - AppLaunchError
      - AppLaunchCompletionHandler