language: objective-c

matrix:
  include:
    - osx_image: xcode9.1

before_install:
  - rvm install 2.4.0

install:
  - gem install cocoapods

script:
  - pod update
  - pod lib lint --allow-warnings
  - cd AppLaunch
  - xcodebuild clean build -workspace AppLaunch.xcworkspace -scheme AppLaunch CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO